# Generated by Django 3.2.5 on 2022-10-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fav',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
